version: '3.0'
services:
  testbh-nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./testbh:/testbh
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    networks:
      - testbh
    ports:
      - "80:80"
  testbh-db:
    build:
      context: ./docker/db      
    container_name: ${PROJECT_NAME}-db
    ports:
      - "54321:5432"
    networks:
      - testbh
  testbh-php:
    build:
      context: ./docker/php
    volumes:
      - ./testbh:/testbh
      # - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-debug.ini
    container_name:  ${PROJECT_NAME}-php
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003" 
    depends_on:
      - testbh-db
    restart: always
    networks:
      - testbh
networks:
  testbh:
    name: testbh               